final_mask_pattern: 'secret' # anonymized
mask_name_pattern: 'secret' # anonymized
mask_name_pattern_efk: 'secret' # anonymized
revision_pattern: 'secret' # anonymized
revision_pattern_efk: 'secret' # anonymized
dataprep_pattern: 'secret' # anonymized
editor_of_choice: 'built_in' # anonymized
run_archive_path: 'secret/run_archive' # anonymized
